version: '3'

services:
  server:
    build:
      context: server
      dockerfile: ../Dockerfile
    command: composer test
    ports:
      - 80:80
    volumes:
      - ./server:/var/www/html
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chez_gustave"]
      interval: 5s
      timeout: 5s
      retries: 5